name: flutter_application
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fancy_on_boarding: ^1.8.0-nullsafety.0
  firebase_core: ^2.10.0

  firebase_core_platform_interface: 4.6.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  google_sign_in: ^6.2.1
google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:  
    - lib\assets/google.png
    - lib\assets\banks.png
    - lib\assets\hotels.png
    - lib\assets\key.png
    - lib\assets\shopping_cart.png
    - lib\assets\stores.png
    - lib\assets\wallet.png
