name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fancy_on_boarding: ^1.8.0-nullsafety.0
  firebase_core: ^2.10.0
  firebase_core_platform_interface: 4.6.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.3
  google_sign_in: ^6.2.1
  image_picker: ^0.8.4+8
  uuid: ^3.0.4
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.0.1-dev
  flutter_markdown: ^0.7.4+1
  http:
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fluttertoast: ^8.0.9
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "lib/assets/images/tree1.png" 
  image_path: "lib/assets/images/tree1.png"

flutter:
  uses-material-design: true
  assets:  
    - lib/assets/images/
    - lib/assets/fonts/
    

 
  
  fonts:
    - family: KitaharaBrush  
      fonts:
        - asset: lib/assets/fonts/KitaharaBrushScript.ttf  
    - family: Lorjuk
      fonts: 
        - asset: lib/assets/fonts/Lorjuk.ttf
        
  
