// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
<<<<<<< HEAD
/// dart
=======
/// ```dart
>>>>>>> 08cf090c12e4c1e1228da177b5ce1fa3328ca40b
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
<<<<<<< HEAD
/// 
=======
/// ```
>>>>>>> 08cf090c12e4c1e1228da177b5ce1fa3328ca40b
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhwhafRJZ0hAdgtsDArZ27dT3wtLzb9zY',
    appId: '1:810171008470:web:eeae3edf97320fca241077',
    messagingSenderId: '810171008470',
    projectId: 'hackathon-2024-4a6c1',
    authDomain: 'hackathon-2024-4a6c1.firebaseapp.com',
    storageBucket: 'hackathon-2024-4a6c1.appspot.com',
    measurementId: 'G-8005Q30TLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-KFw5_StnRRpe7FpGsE2mDbX_EqrU44',
    appId: '1:810171008470:android:05e15375a1720fcc241077',
    messagingSenderId: '810171008470',
    projectId: 'hackathon-2024-4a6c1',
    storageBucket: 'hackathon-2024-4a6c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH_kSTwya-4WvkcE3bCcft41hVfqL9RQo',
    appId: '1:810171008470:ios:d5b4c977c04b0ce6241077',
    messagingSenderId: '810171008470',
    projectId: 'hackathon-2024-4a6c1',
    storageBucket: 'hackathon-2024-4a6c1.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH_kSTwya-4WvkcE3bCcft41hVfqL9RQo',
    appId: '1:810171008470:ios:d5b4c977c04b0ce6241077',
    messagingSenderId: '810171008470',
    projectId: 'hackathon-2024-4a6c1',
    storageBucket: 'hackathon-2024-4a6c1.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhwhafRJZ0hAdgtsDArZ27dT3wtLzb9zY',
    appId: '1:810171008470:web:d90d03788ea07831241077',
    messagingSenderId: '810171008470',
    projectId: 'hackathon-2024-4a6c1',
    authDomain: 'hackathon-2024-4a6c1.firebaseapp.com',
    storageBucket: 'hackathon-2024-4a6c1.appspot.com',
    measurementId: 'G-2XYRD8X45Y',
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> 08cf090c12e4c1e1228da177b5ce1fa3328ca40b
